language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh
env:
  matrix:
  - TEST=ci
  - TEST=plugin SQ_VERSION=6.1
  - TEST=plugin SQ_VERSION=6.2
  - TEST=plugin SQ_VERSION=6.4

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  
dist: precise
